services:
  - type: web
    name: police-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        value: https://copchat-r96a.onrender.com/api
      - key: CORS_ORIGIN
        value: https://chikkaballapurapoliceservice.vercel.app
    healthCheckPath: /
    autoDeploy: true
