import BeatPoliceLayout from "../BeatPoliceLayout";

const beatPoliceInfo = [
  {
    beatNumber: 1,
    officers: [
      {
        name: "Sri Ravindra",
        kannadaName: "ಶ್ರೀ ರವೀಂದ್ರ",
        designation: "CHC-90",
        kannadaDesignation: "ಸಿ.ಹೆಚ್.ಸಿ-90",
        phone: "9743152521",
      },
      {
        name: "Ku. Nagamani",
        kannadaName: "ಕು. ನಾಗಮಣಿ",
        designation: "MPC-225",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-225",
        phone: "8105412913",
      },
    ],
    areas: [
      "Shilemakalhalli",
      "Handiganala",
      "Keshavapura",
      "Hanumenahalli",
      "Appegoudanahalli",
      "Kambadahalli",
      "Meluru",
      "Ganganahalli",
      "Chaudasandra",
      "Ragimakalhalli",
    ],
    kannadaAreas: [
      "ಶಿಲೇಮಾಕಲಹಳ್ಳಿ",
      "ಹಂಡಿಗನಾಳ",
      "ಕೇಶವಾಪುರ",
      "ಹನುಮೇನಹಳ್ಳಿ",
      "ಅಪ್ಪೇಗೌಡನಹಳ್ಳಿ",
      "ಕಂಬದಹಳ್ಳಿ",
      "ಮೇಲೂರು",
      "ಗಂಗನಹಳ್ಳಿ",
      "ಚೌಡಸಂದ್ರ",
      "ರಾಗಿಮಾಕಲಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Srinivasa A",
      kannadaName: "ಶ್ರೀ ಶ್ರೀನಿವಾಸ ಎ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9686438804",
    },
  },
  {
    beatNumber: 2,
    officers: [
      {
        name: "Sri Maruti Niravari",
        kannadaName: "ಶ್ರೀ ಮಾರುತಿ ನಿರಾವರಿ",
        designation: "CPC-391",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-391",
        phone: "7353846170",
      },
      {
        name: "Sri Satyappa Kareppa Jatti",
        kannadaName: "ಶ್ರೀ ಸತ್ಯಪ್ಪ ಕರೆಪ್ಪ ಜಟ್ಟಿ",
        designation: "CPC-418",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-418",
        phone: "9945804868",
      },
    ],
    areas: [
      "Anuru",
      "A.Hunasenahalli",
      "Tippenahalli",
      "Dabarganahalli",
      "Bairanayakanahalli",
      "Japti Hosahalli",
      "Bodaguru",
      "Hittalahalli",
      "Belluti",
      "Bhaktahalli",
    ],
    kannadaAreas: [
      "ಆನೂರು",
      "ಎ.ಹುಣಸೇನಹಳ್ಳಿ",
      "ತಿಪ್ಪೇನಹಳ್ಳಿ",
      "ಡಬರಗಾನಹಳ್ಳಿ",
      "ಬೈರನಾಯಕನಹಳ್ಳಿ",
      "ಜಪ್ತಿ ಹೊಸಹಳ್ಳಿ",
      "ಬೋದಗೂರು",
      "ಹಿತ್ತಲಹಳ್ಳಿ",
      "ಬೆಳ್ಳೂಟಿ",
      "ಭಕ್ತಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Srinivasa A",
      kannadaName: "ಶ್ರೀ ಶ್ರೀನಿವಾಸ ಎ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9686438804",
    },
  },
  {
    beatNumber: 3,
    officers: [
      {
        name: "Sri Manjunath",
        kannadaName: "ಶ್ರೀ ಮಂಜುನಾಥ್",
        designation: "CPC-91",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-91",
        phone: "9591684860",
      },
      {
        name: "Smt. Shweta",
        kannadaName: "ಶ್ರೀಮತಿ ಶ್ವೇತಾ",
        designation: "MPC-251",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-251",
        phone: "9148582320",
      },
    ],
    areas: [
      "Malluru",
      "Matturu",
      "Kachahalli",
      "Ankattatti",
      "Kakachakkondahalli",
      "Nagamangala",
      "Hosahalli",
      "Nallenahalli",
      "Nadipinaayakanahalli",
      "Pura (Be)",
    ],
    kannadaAreas: [
      "ಮಳ್ಳೂರು",
      "ಮತ್ತೂರು",
      "ಕಾಚಹಳ್ಳಿ",
      "ಅಂಕತಟ್ಟಿ",
      "ಕಾಕಚಕ್ಕೊಂಡಹಳ್ಳಿ",
      "ನಾಗಮಂಗಲ",
      "ಹೊಸಹಳ್ಳಿ",
      "ನಲ್ಲೇನಹಳ್ಳಿ",
      "ನಡಿಪಿನಾಯಕನಹಳ್ಳಿ",
      "ಪುರ (ಬೇ)",
    ],
    supervisor: {
      name: "Sri Srinivasa A",
      kannadaName: "ಶ್ರೀ ಶ್ರೀನಿವಾಸ ಎ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9686438804",
    },
  },
  {
    beatNumber: 4,
    officers: [
      {
        name: "Sri Raju",
        kannadaName: "ಶ್ರೀ ರಾಜು",
        designation: "CHC-136",
        kannadaDesignation: "ಸಿ.ಹೆಚ್.ಸಿ-136",
        phone: "9740242414",
      },
      {
        name: "Sri Mutturaj",
        kannadaName: "ಶ್ರೀ ಮುತ್ತುರಾಜ್",
        designation: "CPC-144",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-144",
        phone: "9902312624",
      },
    ],
    areas: [
      "Mugiladapi",
      "Malamachanahalli",
      "Basavapattana",
      "Taduru",
      "Totliganahalli",
      "Yannanguru",
      "Doddachakkondahalli",
      "Eddalatippenahalli",
      "Hosapete",
    ],
    kannadaAreas: [
      "ಮುಗಿಲಡಪಿ",
      "ಮಳಮಾಚನಹಳ್ಳಿ",
      "ಬಸವಾಪಟ್ಟಣ",
      "ತಾದೂರು",
      "ತೊಟ್ಲಿಗಾನಹಳ್ಳಿ",
      "ಯಣ್ಣಂಗೂರು",
      "ದೊಡ್ಡಚಕ್ಕೊಂಡಹಳ್ಳಿ",
      "ಎದ್ದಲತಿಪ್ಪೇನಹಳ್ಳಿ",
      "ಹೊಸಪೇಟೆ",
    ],
    supervisor: {
      name: "Sri Srinivasa A",
      kannadaName: "ಶ್ರೀ ಶ್ರೀನಿವಾಸ ಎ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9686438804",
    },
  },
  {
    beatNumber: 5,
    officers: [
      {
        name: "Sri Venkatesh",
        kannadaName: "ಶ್ರೀ ವೆಂಕಟೇಶ್",
        designation: "CPC-126",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-126",
        phone: "9611176337",
      },
      {
        name: "Sri Gangadhar",
        kannadaName: "ಶ್ರೀ ಗಂಗಾಧರ್",
        designation: "CPC-291",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-291",
        phone: "7676334090",
      },
    ],
    areas: [
      "Jangamakote/Cross",
      "Obalapura",
      "J.Kurabarahalli",
      "Tottibavi",
      "K.G Chikkaballa",
      "Sundrahalli",
      "Bairasandra",
      "Sugaturu",
      "Ghattamaranahalli",
      "J.Venkatapura",
      "Baluvanahalli",
      "Mittanahalli",
    ],
    kannadaAreas: [
      "ಜಂಗಮಕೋಟೆ/ಕ್ರಾಸ್",
      "ಓಬಳಾಪುರ",
      "ಜೆ.ಕುರಬರಹಳ್ಳಿ",
      "ತೊಟ್ಟಿಬಾವಿ",
      "ಕೆ.ಜಿ ಚಿಕ್ಕಬಲ್ಲ",
      "ಸುಂಡ್ರಹಳ್ಳಿ",
      "ಬೈರಸಂದ್ರ",
      "ಸುಗಟೂರು",
      "ಘಟ್ಟಮಾರನಹಳ್ಳಿ",
      "ಜೆ.ವೆಂಕಟಾಪುರ",
      "ಬಳುವನಹಳ್ಳಿ",
      "ಮಿತ್ತನಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Srinivasa A",
      kannadaName: "ಶ್ರೀ ಶ್ರೀನಿವಾಸ ಎ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9686438804",
    },
  },
  {
    beatNumber: 6,
    officers: [
      {
        name: "Sri Mylarappa",
        kannadaName: "ಶ್ರೀ ಮೈಲಾರಪ್ಪ",
        designation: "CPC-310",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-310",
        phone: "9972856764",
      },
      {
        name: "Sri Balakrishna M.N",
        kannadaName: "ಶ್ರೀ ಬಾಲಕೃಷ್ಣ ಎಂ.ಎನ್",
        designation: "CPC-349",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-349",
        phone: "7795669177",
      },
    ],
    areas: [
      "H.Cross",
      "Kariyanapura",
      "Kumbiganahalli",
      "Ambiganahalli",
      "Devenahalli",
      "Kalanayakanahalli",
      "Gambhiranahalli",
      "Mallenahalli",
      "Kalyapura",
      "Fakiranahosahalli",
    ],
    kannadaAreas: [
      "ಹೆಚ್.ಕ್ರಾಸ್",
      "ಕರಿಯನಪುರ",
      "ಕುಂಭಿಗಾನಹಳ್ಳಿ",
      "ಅಂಭಿಗಾನಹಳ್ಳಿ",
      "ದೇವೇನಹಳ್ಳಿ",
      "ಕಾಳನಾಯಕನಹಳ್ಳಿ",
      "ಗಂಭೀರನಹಳ್ಳಿ",
      "ಮಲ್ಲೇನಹಳ್ಳಿ",
      "ಕಲ್ಯಾಪುರ",
      "ಫಕೀರನಹೊಸಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Srinivasa A",
      kannadaName: "ಶ್ರೀ ಶ್ರೀನಿವಾಸ ಎ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9686438804",
    },
  },
  {
    beatNumber: 7,
    officers: [
      {
        name: "Sri Maibusab H Dapedar",
        kannadaName: "ಶ್ರೀ ಮೈಬುಸಾಬ್ ಹೆಚ್ ಡಾಪೇದಾರ್",
        designation: "CPC-406",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-406",
        phone: "8147857295",
      },
      {
        name: "Smt. Jamuna",
        kannadaName: "ಶ್ರೀಮತಿ ಜಮುನಾ",
        designation: "MPC-229",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-229",
        phone: "7338622723",
      },
    ],
    areas: [
      "Devaganahalli",
      "Hireballa",
      "Vallappanahalli",
      "Tatapatri",
      "Krishnahalli",
      "Attiganahalli",
      "Arikere",
      "Sanjeevarayanapura",
      "Yarrachannapura",
    ],
    kannadaAreas: [
      "ದೇವಗಾನಹಳ್ಳಿ",
      "ಹಿರೇಬಲ್ಲ",
      "ವಲ್ಲಪ್ಪನಹಳ್ಳಿ",
      "ತಾಟಪತ್ರಿ",
      "ಕೃಷ್ಣಹಳ್ಳಿ",
      "ಅತ್ತಿಗಾನಹಳ್ಳಿ",
      "ಅರಿಕೆರೆ",
      "ಸಂಜೀವರಾಯನಪುರ",
      "ಯರ್ರಚನ್ನಾಪುರ",
    ],
    supervisor: {
      name: "Sri Srinivasa A",
      kannadaName: "ಶ್ರೀ ಶ್ರೀನಿವಾಸ ಎ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9686438804",
    },
  },
  {
    beatNumber: 8,
    officers: [
      {
        name: "Sri Altaf",
        kannadaName: "ಶ್ರೀ ಅಲ್ತಾಫ್",
        designation: "CPC-215",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-215",
        phone: "9538499778",
      },
      {
        name: "Sri Lakshman",
        kannadaName: "ಶ್ರೀ ಲಕ್ಷ್ಮಣ್",
        designation: "CPC-422",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-422",
        phone: "7349534631",
      },
    ],
    areas: [
      "Narayanadaasarahalli",
      "Cheemangala",
      "Yannuru",
      "K.G Pura",
      "Hemarlahalli",
      "Haradi",
      "K.Hosuru",
      "Amaravati",
      "K.Gollahalli",
      "T.Bussanahalli",
    ],
    kannadaAreas: [
      "ನಾರಾಯಣದಾಸರಹಳ್ಳಿ",
      "ಚೀಮಂಗಲ",
      "ಯಣ್ಣೂರು",
      "ಕೆ.ಜಿ ಪುರ",
      "ಹೇಮಾರ್ಲಹಳ್ಳಿ",
      "ಹಾರಡಿ",
      "ಕೆ.ಹೊಸೂರು",
      "ಅಮಾರವತಿ",
      "ಕೆ.ಗೊಲ್ಲಹಳ್ಳಿ",
      "ಟಿ.ಬುಸ್ಸನಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Subramani V",
      kannadaName: "ಶ್ರೀ ಸುಬ್ರಮಣಿ ವಿ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9449529191",
    },
  },
  {
    beatNumber: 9,
    officers: [
      {
        name: "Sri Ashwathayya",
        kannadaName: "ಶ್ರೀ ಅಶ್ವತ್ಥಯ್ಯ",
        designation: "CHC-154",
        kannadaDesignation: "ಸಿ.ಹೆಚ್.ಸಿ-154",
        phone: "9632141129",
      },
      {
        name: "Sri Renuka Hiremani",
        kannadaName: "ಶ್ರೀ ರೇಣುಕಾ ಹಿರೇಮಣಿ",
        designation: "MPC-350",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-350",
        phone: "8746959113",
      },
    ],
    areas: [
      "Bhudala",
      "Veerapura",
      "Taladummanahalli",
      "Bachchahalli",
      "Devaramalluru",
      "Pindipappanahalli",
      "Bommanahalli",
      "Birappanahalli",
      "Marappanahalli",
      "Sonnenahalli",
      "Basavanapatti",
    ],
    kannadaAreas: [
      "ಭೂದಾಳ",
      "ವೀರಾಪುರ",
      "ತಲದುಮ್ಮನಹಳ್ಳಿ",
      "ಬಚ್ಚಹಳ್ಳಿ",
      "ದೇವರಮಳ್ಳೂರು",
      "ಪಿಂಡಿಪಾಪನಹಳ್ಳಿ",
      "ಬೊಮ್ಮನಹಳ್ಳಿ",
      "ಬೀರಪ್ಪನಹಳ್ಳಿ",
      "ಮಾರಪ್ಪನಹಳ್ಳಿ",
      "ಸೊಣ್ಣೇನಹಳ್ಳಿ",
      "ಬಸವನಪತ್ತಿ",
    ],
    supervisor: {
      name: "Sri Subramani V",
      kannadaName: "ಶ್ರೀ ಸುಬ್ರಮಣಿ ವಿ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9449529191",
    },
  },
  {
    beatNumber: 10,
    officers: [
      {
        name: "Sri Chetan",
        kannadaName: "ಶ್ರೀ ಚೇತನ್",
        designation: "CPC-40",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-40",
        phone: "7676214166",
      },
      {
        name: "Sri Satish",
        kannadaName: "ಶ್ರೀ ಸತೀಶ್",
        designation: "CPC-289",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-289",
        phone: "9901500126",
      },
    ],
    areas: [
      "Chikkadaasarahalli",
      "Doddadasarahalli",
      "Sorakayalahalli",
      "Tummanahalli",
      "Gudlanarasimhanahalli",
      "Mallishettipura",
      "Kuppenahalli",
      "Hujaguru",
      "Halasoorudinne",
      "Chintadapi",
      "K.Muttukadahalli",
    ],
    kannadaAreas: [
      "ಚಿಕ್ಕದಾಸರಹಳ್ಳಿ",
      "ದೊಡ್ಡದಾಸರಹಳ್ಳಿ",
      "ಸೊರಕಾಯಲಹಳ್ಳಿ",
      "ತುಮ್ಮನಹಳ್ಳಿ",
      "ಗುಡ್ಲನರಸಿಂಹನಹಳ್ಳಿ",
      "ಮಲ್ಲಿಶೆಟ್ಟಿಪುರ",
      "ಕುಪ್ಪೇನಹಳ್ಳಿ",
      "ಹುಜಗೂರು",
      "ಹಲಸೂರುದಿನ್ನೆ",
      "ಚಿಂತಡಪಿ",
      "ಕೆ.ಮುತ್ತುಕದಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Subramani V",
      kannadaName: "ಶ್ರೀ ಸುಬ್ರಮಣಿ ವಿ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9449529191",
    },
  },
  {
    beatNumber: 11,
    officers: [
      {
        name: "Sri Anand Kumar",
        kannadaName: "ಶ್ರೀ ಆನಂದ್ ಕುಮಾರ್",
        designation: "CHC-96",
        kannadaDesignation: "ಸಿ.ಹೆಚ್.ಸಿ-96",
        phone: "7996407664",
      },
    ],
    areas: [
      "Kadirinayakanahalli",
      "Y.Hunasenahalli/Station",
      "Shigehalli",
      "Gejjiganahalli",
      "Channahalli",
      "Goramadagu",
      "Chikkadasenahalli",
      "Doddadasenahalli",
      "Chikkappapenahalli",
      "B.Hosahalli",
      "Kottanuru",
    ],
    kannadaAreas: [
      "ಕದಿರಿನಾಯಕನಹಳ್ಳಿ",
      "ವೈ.ಹುಣಸೇನಹಳ್ಳಿ/ಸ್ಟೇಷನ್",
      "ಶಿಗೇಹಳ್ಳಿ",
      "ಗೆಜ್ಜಿಗಾನಹಳ್ಳಿ",
      "ಚನ್ನಹಳ್ಳಿ",
      "ಗೊರಮಡಗು",
      "ಚಿಕ್ಕದಾಸೇನಹಳ್ಳಿ",
      "ದೊಡ್ಡದಾಸೇನಹಳ್ಳಿ",
      "ಚಿಕ್ಕಪಾಪೇನಹಳ್ಳಿ",
      "ಬಿ.ಹೊಸಹಳ್ಳಿ",
      "ಕೊತ್ತನೂರು",
    ],
    supervisor: {
      name: "Sri Subramani V",
      kannadaName: "ಶ್ರೀ ಸುಬ್ರಮಣಿ ವಿ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9449529191",
    },
  },
  {
    beatNumber: 12,
    officers: [
      {
        name: "Sri Nataraj",
        kannadaName: "ಶ್ರೀ ನಟರಾಜ್",
        designation: "CHC-16",
        kannadaDesignation: "ಸಿ.ಹೆಚ್.ಸಿ-16",
        phone: "9840862636",
      },
      {
        name: "Smt. Ambika",
        kannadaName: "ಶ್ರೀಮತಿ ಅಂಬಿಕಾ",
        designation: "MPC-160",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-160",
        phone: "",
      },
    ],
    areas: [
      "Hanumantapura",
      "Varadanayakanahalli",
      "Haralahalli",
      "Tatahalli",
      "Cheemanahalli",
      "Abludu",
      "Chage",
      "Vankamaradahalli",
      "Kempanahalli",
    ],
    kannadaAreas: [
      "ಹನುಮಂತಪುರ",
      "ವರದನಾಯಕನಹಳ್ಳಿ",
      "ಹರಳಹಳ್ಳಿ",
      "ತಾತಹಳ್ಳಿ",
      "ಚೀಮನಹಳ್ಳಿ",
      "ಅಬ್ಲೂಡು",
      "ಚಾಗೆ",
      "ವಂಕಮರದಹಳ್ಳಿ",
      "ಕೆಂಪನಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Subramani V",
      kannadaName: "ಶ್ರೀ ಸುಬ್ರಮಣಿ ವಿ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9449529191",
    },
  },
  {
    beatNumber: 13,
    officers: [
      {
        name: "Sri Raghavendra",
        kannadaName: "ಶ್ರೀ ರಾಘವೇಂದ್ರ",
        designation: "CHC-15",
        kannadaDesignation: "ಸಿ.ಹೆಚ್.ಸಿ-15",
        phone: "9840862636",
      },
      {
        name: "Sri Harish M",
        kannadaName: "ಶ್ರೀ ಹರೀಶ್ ಎಂ",
        designation: "CPC-428",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-428",
        phone: "",
      },
    ],
    areas: [
      "Kundalagurki",
      "Rupalarhalli",
      "Jodikachahalli",
      "Gangapura",
      "Parlichelru",
      "Donnahalli",
      "Gollahalli",
      "Siddapura",
      "Varahunasenahalli",
      "Dogaranayakanahalli",
      "Kuttandahalli",
      "Idludu",
    ],
    kannadaAreas: [
      "ಕುಂದಲಗುರ್ಕಿ",
      "ರೂಪಾಲರ್ಹಳ್ಳಿ",
      "ಜೋಡಿಕಾಚಹಳ್ಳಿ",
      "ಗಂಗಾಪುರ",
      "ಪರ್ಲಿಚೆಲ್ರು",
      "ದೊಣ್ಣಹಳ್ಳಿ",
      "ಗೊಲ್ಲಹಳ್ಳಿ",
      "ಸಿದ್ದಾಪುರ",
      "ವಾರಹುಣಸೇನಹಳ್ಳಿ",
      "ದೊಗರನಾಯಕನಹಳ್ಳಿ",
      "ಕುತ್ತಾಂಡಹಳ್ಳಿ",
      "ಇದ್ಲೂಡು",
    ],
    supervisor: {
      name: "Sri Subramani V",
      kannadaName: "ಶ್ರೀ ಸುಬ್ರಮಣಿ ವಿ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9449529191",
    },
  },
  {
    beatNumber: 14,
    officers: [
      {
        name: "Sri Nagaveni",
        kannadaName: "ಶ್ರೀ ನಾಗವೇಣಿ",
        designation: "MHCC-21",
        kannadaDesignation: "ಎಂ.ಹೆಚ್.ಸಿ.ಸಿ-21",
        phone: "9742226531",
      },
      {
        name: "Sri Jagadish",
        kannadaName: "ಶ್ರೀ ಜಗದೀಶ್",
        designation: "CPC-384",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-384",
        phone: "",
      },
    ],
    areas: [
      "L.Muttukadahalli",
      "Pailahalli",
      "Lakkahalli",
      "Nellimaradahalli",
      "Kurubachanapade",
      "Gudihalli",
      "Shettihalli",
      "Mallenahalli",
      "Kotahalli",
    ],
    kannadaAreas: [
      "ಎಲ್.ಮುತ್ತುಕದಹಳ್ಳಿ",
      "ಪೈಲಹಳ್ಳಿ",
      "ಲಕ್ಕಹಳ್ಳಿ",
      "ನೆಲ್ಲಿಮರದಹಳ್ಳಿ",
      "ಕುರುಬಚ್ಚನಪಡೆ",
      "ಗುಡಿಹಳ್ಳಿ",
      "ಶೆಟ್ಟಿಹಳ್ಳಿ",
      "ಮಲ್ಲೇನಹಳ್ಳಿ",
      "ಕೋಟಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Subramani V",
      kannadaName: "ಶ್ರೀ ಸುಬ್ರಮಣಿ ವಿ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9449529191",
    },
  },
];

export default function ShidlaghattaRural() {
  // Transform the data into the expected format
  const transformedData = {
    beatDetails: beatPoliceInfo.map(beat => ({
      number: beat.beatNumber,
      villages: beat.areas.map((area, index) => ({
        en: area,
        kn: beat.kannadaAreas[index]
      })),
      officers: beat.officers.map(officer => ({
        name: {
          en: officer.name,
          kn: officer.kannadaName
        },
        designation: {
          en: officer.designation,
          kn: officer.kannadaDesignation
        },
        phone: officer.phone
      })),
      supervisor: {
        name: {
          en: beat.supervisor.name,
          kn: beat.supervisor.kannadaName
        },
        designation: {
          en: beat.supervisor.designation,
          kn: beat.supervisor.kannadaDesignation
        },
        phone: beat.supervisor.phone
      }
    })),
    supervisingOfficers: Array.from(new Set(beatPoliceInfo.map(beat => beat.supervisor.name))).map(supervisorName => {
      const supervisor = beatPoliceInfo.find(beat => beat.supervisor.name === supervisorName).supervisor;
      const supervisedBeats = beatPoliceInfo
        .filter(beat => beat.supervisor.name === supervisorName)
        .map(beat => beat.beatNumber)
        .join(", ");
      
      return {
        beats: supervisedBeats,
        name: {
          en: supervisor.name,
          kn: supervisor.kannadaName
        },
        designation: {
          en: supervisor.designation,
          kn: supervisor.kannadaDesignation
        },
        phone: supervisor.phone
      };
    })
  };

  return (
    <BeatPoliceLayout 
      beatData={transformedData}
      talukName={{
        en: "Shidlaghatta Rural",
        kn: "ಶಿಡ್ಲಘಟ್ಟ ಗ್ರಾಮೀಣ"
      }}
    />
  );
} 