import BeatPoliceLayout from "../BeatPoliceLayout";

const beatPoliceInfo = [
  {
    beatNumber: 1,
    officers: [
      {
        name: "Sri Shivappa",
        kannadaName: "ಶ್ರೀ ಶಿವಪ್ಪ",
        designation: "HC-210",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-210",
        phone: "9611188805",
      },
      {
        name: "Ku. Devika",
        kannadaName: "ಕು. ದೇವಿಕಾ",
        designation: "MPC-283",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-283",
        phone: "7483317323",
      },
    ],
    areas: [
      "Bhaktarahalli",
      "Ulappanahalli",
      "Korlahalli",
      "Chandrahalli",
      "Kattariguppe",
      "Husseinpura",
      "Kadashanahalli",
      "Timmasandra",
      "Mohammadpura",
      "Kanganahalli",
    ],
    kannadaAreas: [
      "ಭಕ್ತರಹಳ್ಳಿ",
      "ಉಲಪ್ಪನಹಳ್ಳಿ",
      "ಕೊರ್ಲಹಳ್ಳಿ",
      "ಚಾಂಡ್ರಹಳ್ಳಿ",
      "ಕತ್ತರಿಗುಪ್ಪೆ",
      "ಹುಸ್ಸೇನ್ಪುರ",
      "ಕಡಶಾನಹಳ್ಳಿ",
      "ತಿಮ್ಮಸಂದ್ರ",
      "ಮೊಹಮ್ಮದ್ಪುರ",
      "ಕಂಗಾನಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Dinesh",
      kannadaName: "ಶ್ರೀ ದಿನೇಶ್",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9207908003",
    },
  },
  {
    beatNumber: 2,
    officers: [
      {
        name: "Sri Bairoji Rao",
        kannadaName: "ಶ್ರೀ ಬೈರೋಜಿ ರಾವ್",
        designation: "HC-67",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-67",
        phone: "9141110941",
      },
      {
        name: "Sri Vinayaka",
        kannadaName: "ಶ್ರೀ ವಿನಾಯಕ",
        designation: "CPC-441",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-441",
        phone: "6361895521",
      },
    ],
    areas: [
      "Bukkanahalli",
      "Singasandra",
      "N.Kotturu",
      "K.Gollahalli",
      "Doddahalli",
      "Kurumaralahalli",
      "Sujjanahalli",
      "Narasapura",
      "Kotagal",
      "K.Raguttahalli",
      "Chaudadenahalli",
      "Bandameedahalli",
      "Bodanamari",
      "Nallarallahalli Cross",
    ],
    kannadaAreas: [
      "ಬುಕ್ಕನಹಳ್ಳಿ",
      "ಸಿಂಗಸಂದ್ರ",
      "ಎನ್.ಕೊತ್ತೂರು",
      "ಕೆ.ಗೊಲ್ಲಹಳ್ಳಿ",
      "ದೊಡ್ಡಹಳ್ಳಿ",
      "ಕುರುಮಾರ್ಲಹಳ್ಳಿ",
      "ಸುಜ್ಜನಹಳ್ಳಿ",
      "ನರಸಾಪುರ",
      "ಕೋಟಗಲ್",
      "ಕೆ.ರಾಗುಟ್ಟಹಳ್ಳಿ",
      "ಚೌಡದೇನಹಳ್ಳಿ",
      "ಬಂಡಮೀದಹಳ್ಳಿ",
      "ಬೋಡನಮರಿ",
      "ನಲ್ಲರಾಳ್ಳಹಳ್ಳಿಕ್ರಾಸ್",
    ],
    supervisor: {
      name: "Sri Intiyaz",
      kannadaName: "ಶ್ರೀ ಇಂತಿಯಾಜ್",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9741903034",
    },
  },
  {
    beatNumber: 3,
    officers: [
      {
        name: "Sri Ishwar",
        kannadaName: "ಶ್ರೀ ಈಶ್ವರ್",
        designation: "HC-196",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-196",
        phone: "8073007718",
      },
      {
        name: "Sri Ashok",
        kannadaName: "ಶ್ರೀ ಅಶೋಕ್",
        designation: "CPC-287",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-287",
        phone: "9945078465",
      },
    ],
    areas: [
      "Chokkanahalli",
      "Nayanhalli",
      "Srinivasapura",
      "Venkatapura",
      "Ketanayakanahalli",
      "Yashwantapura",
      "Palepalli",
      "Jaladenahalli",
      "Shettihalli",
      "Anakal",
      "Tammepalli",
      "Chikkamunimangala",
      "Doddamunimangala",
      "Kodigenahalli",
      "Nelamachanahalli",
    ],
    kannadaAreas: [
      "ಚೊಕ್ಕನಹಳ್ಳಿ",
      "ನಾಯನಹಳ್ಳಿ",
      "ಶ್ರೀನಿವಾಸಪುರ",
      "ವೆಂಕಟಾಪುರ",
      "ಕೇತನಾಯಕನಹಳ್ಳಿ",
      "ಯಶವಂತಪುರ",
      "ಪಾಲೇಪಲ್ಲಿ",
      "ಜಲದೇನಹಳ್ಳಿ",
      "ಶೆಟ್ಟಿಹಳ್ಳಿ",
      "ಅನಕಲ್",
      "ತಮ್ಮೇಪಲ್ಲಿ",
      "ಚಿಕ್ಕಮುನಿಮಂಗಲ",
      "ದೊಡ್ಡಮುನಿಮಂಗಲ",
      "ಕೋಡಿಗೇನಹಳ್ಳಿ",
      "ನೆಲಮಾಚನಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Intiyaz",
      kannadaName: "ಶ್ರೀ ಇಂತಿಯಾಜ್",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9741903034",
    },
  },
  {
    beatNumber: 4,
    officers: [
      {
        name: "Sri Nagabhushan",
        kannadaName: "ಶ್ರೀ ನಾಗಭೂಷಣ್",
        designation: "HC-126",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-126",
        phone: "9945262435",
      },
      {
        name: "Sri Timmesh",
        kannadaName: "ಶ್ರೀ ತಿಮ್ಮೇಶ್",
        designation: "CPC-412",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-412",
        phone: "6361333091",
      },
    ],
    areas: [
      "Chokkareddihalli",
      "Krishnarajapura",
      "Tippanahalli",
      "Veerapalli",
      "Jagattanahalli",
      "Gopalapura",
      "Bacchavarahalli",
      "Kagati",
      "Hiranyahalli",
      "Kongatimmanahalli",
      "Badagavarahalli",
      "Kariyapalli",
    ],
    kannadaAreas: [
      "ಚೊಕ್ಕರೆಡ್ಡಿಹಳ್ಳಿ",
      "ಕೃಷ್ಣರಾಜಪುರ",
      "ತಿಪ್ಪನಹಳ್ಳಿ",
      "ವೀರಪಲ್ಲಿ",
      "ಜಗತ್ತನಹಳ್ಳಿ",
      "ಗೋಪಾಲಪುರ",
      "ಬಚ್ಚವಾರಹಳ್ಳಿ",
      "ಕಾಗತಿ",
      "ಹೀರಣ್ಯಹಳ್ಳಿ",
      "ಕೊಂಗತಿಮ್ಮನಹಳ್ಳಿ",
      "ಬಡಗವಾರಹಳ್ಳಿ",
      "ಕರಿಯಪಲ್ಲಿ",
    ],
    supervisor: {
      name: "Sri Nanjundegowda",
      kannadaName: "ಶ್ರೀ ನಂಜುಂಡೇಗೌಡ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9740082030",
    },
  },
  {
    beatNumber: 5,
    officers: [
      {
        name: "Sri Shashikumar",
        kannadaName: "ಶ್ರೀ ಶಶಿಕುಮಾರ್",
        designation: "HC-138",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-138",
        phone: "9738279374",
      },
      {
        name: "Ku. Prema",
        kannadaName: "ಕು. ಪ್ರೇಮ",
        designation: "MPC-378",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-378",
        phone: "9901796984",
      },
    ],
    areas: [
      "Gopasandra",
      "Buragamakalhalli",
      "Handijogigadda",
      "Ulavadi",
      "Kurapalli",
      "Bhattalhalli",
      "Hebbari",
      "Aimareddihalli",
      "Cheemanahalli",
    ],
    kannadaAreas: ["ಗೋಪಸಂದ್ರ", "ಬೂರಗಮಾಕಲಹಳ್ಳಿ", "ಹಂದಿಜೋಗಿಗಡ್ಡ", "ಊಲವಾಡಿ", "ಕುರಪಲ್ಲಿ", "ಭತ್ತಲಹಳ್ಳಿ", "ಹೆಬ್ಬರಿ", "ಐಮರೆಡ್ಡಿಹಳ್ಳಿ", "ಚೀಮನಹಳ್ಳಿ"],
    supervisor: {
      name: "Sri Nanjundegowda",
      kannadaName: "ಶ್ರೀ ನಂಜುಂಡೇಗೌಡ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9740082030",
    },
  },
  {
    beatNumber: 6,
    officers: [
      {
        name: "Sri Ejaz Pasha",
        kannadaName: "ಶ್ರೀ ಎಜಾಜ್ ಪಾಷಾ",
        designation: "HC-200",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-200",
        phone: "7760853525",
      },
      {
        name: "Sri Ashok",
        kannadaName: "ಶ್ರೀ ಅಶೋಕ್",
        designation: "CPC-78",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-78",
        phone: "8197988915",
      },
    ],
    areas: [
      "Doddaganjuru",
      "Kodadavadi",
      "Siddimath",
      "Gollahalli",
      "G.Kodihalli",
      "Singanahalli",
      "K.Hosuru",
      "Doddanatta",
      "Hadigere",
      "Mudachintalhalli",
      "Madikere",
    ],
    kannadaAreas: [
      "ದೊಡ್ಡಗಂಜೂರು",
      "ಕೊಡದವಾಡಿ",
      "ಸಿದ್ದಿಮಠ",
      "ಗೊಲ್ಲಹಳ್ಳಿ",
      "ಜಿ.ಕೋಡಿಹಳ್ಳಿ",
      "ಸಿಂಗನಹಳ್ಳಿ",
      "ಕೆ.ಹೊಸೂರು",
      "ದೊಡ್ಡನತ್ತ",
      "ಹಾದಿಗೆರೆ",
      "ಮೂಡಚಿಂತಲಹಳ್ಳಿ",
      "ಮಾಡಿಕೆರೆ",
    ],
    supervisor: {
      name: "Sri Narasimha",
      kannadaName: "ಶ್ರೀ ನರಸಿಂಹ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9900721313",
    },
  },
  {
    beatNumber: 7,
    officers: [
      {
        name: "Sri Chandrappa",
        kannadaName: "ಶ್ರೀ ಚಂದ್ರಪ್ಪ",
        designation: "HC-30",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-30",
        phone: "9731381138",
      },
      {
        name: "Smt. Mousina Taj",
        kannadaName: "ಶ್ರೀಮತಿ ಮೌಸಿನಾ ತಾಜ್",
        designation: "MPC-170",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-170",
        phone: "7899491334",
      },
    ],
    areas: [
      "Anuru",
      "Krishnamanahosahalli",
      "Chikkapura",
      "Doddapura",
      "Vishwanatapura",
      "Kuruburu",
      "Yadahalli",
      "Seekallu",
      "Chikkabommahalli",
      "Doddabommanahalli",
      "Panasachaudanahalli",
      "Mailandahalli",
      "Gadadasanahalli",
      "Kutarajanahalli",
    ],
    kannadaAreas: [
      "ಆನೂರು",
      "ಕೃಷ್ಣಮನಹೊಸಹಳ್ಳಿ",
      "ಚಿಕ್ಕಪುರ",
      "ದೊಡ್ಡಪುರ",
      "ವಿಶ್ವನಾಥಪುರ",
      "ಕುರುಬೂರು",
      "ಯಡಹಳ್ಳಿ",
      "ಸೀಕಲ್ಲು",
      "ಚಿಕ್ಕಬೊಮ್ಮಹಳ್ಳಿ",
      "ದೊಡ್ಡಬೊಮ್ಮನಹಳ್ಳಿ",
      "ಪಣಸಚೌಡನಹಳ್ಳಿ",
      "ಮೈಲಾಂಡಹಳ್ಳಿ",
      "ಗಡದಾಸನಹಳ್ಳಿ",
      "ಕೂತರಾಜನಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Narasimha",
      kannadaName: "ಶ್ರೀ ನರಸಿಂಹ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9900721313",
    },
  },
  {
    beatNumber: 8,
    officers: [
      {
        name: "Sri Ramakrishna",
        kannadaName: "ಶ್ರೀ ರಾಮಕೃಷ್ಣ",
        designation: "HC-71",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-71",
        phone: "9164846471",
      },
      {
        name: "Sri Krishnamurthy",
        kannadaName: "ಶ್ರೀ ಕೃಷ್ಣಮೂರ್ತಿ",
        designation: "CPC-182",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-182",
        phone: "9036665896",
      },
    ],
    areas: [
      "Ambedkar Nagar",
      "Rampura",
      "Kurutahalli",
      "Kachahalli",
      "Brahmaradinne",
      "Bidaganahalli",
      "Suladenahalli",
      "Gajalahalli",
      "Bandarlahalli",
      "Nidagurki",
      "Chennakeshavapura",
      "A.Hosahalli",
    ],
    kannadaAreas: [
      "ಅಂಬೇಡ್ಕರ್ನಗರ",
      "ರಾಂಪುರ",
      "ಕುರುಟಹಳ್ಳಿ",
      "ಕಾಚಹಳ್ಳಿ",
      "ಬ್ರಾಹ್ಮಣರದಿನ್ನೆ",
      "ಬಿಡಗಾನಹಳ್ಳಿ",
      "ಸೂಲದೇನಹಳ್ಳಿ",
      "ಗಾಜಲಹಳ್ಳಿ",
      "ಬಂದಾರ್ಲಹಳ್ಳಿ",
      "ನಿಡಗುರ್ಕಿ",
      "ಚೆನ್ನಕೇಶವಪುರ",
      "ಎ.ಹೊಸಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Harish",
      kannadaName: "ಶ್ರೀ ಹರೀಶ್",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9740704290",
    },
  },
  {
    beatNumber: 9,
    officers: [
      {
        name: "Sri Krishnappa",
        kannadaName: "ಶ್ರೀ ಕೃಷ್ಣಪ್ಪ",
        designation: "CPC-524",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-524",
        phone: "9036665896",
      },
      {
        name: "Sri Parushuram",
        kannadaName: "ಶ್ರೀ ಪರುಶುರಾಮ್",
        designation: "CPC-407",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-407",
        phone: "9964263425",
      },
    ],
    areas: [
      "Kannampalli",
      "Katamachanahalli",
      "Chinnasandra",
      "Kallahalli",
      "Nallaguttahalli",
      "Doddahalli",
      "Chapura",
      "Kendanahalli",
      "Alambagiri",
      "Peramachanahalli",
      "Munuganahalli",
      "Nayindrahalli",
      "Venkatapura",
    ],
    kannadaAreas: [
      "ಕನ್ನಂಪಲ್ಲಿ",
      "ಕಟಮಾಚನಹಳ್ಳಿ",
      "ಚಿನ್ನಸಂದ್ರ",
      "ಕಲ್ಲಹಳ್ಳಿ",
      "ನಲ್ಲಗುಟ್ಟಹಳ್ಳಿ",
      "ದೊಡ್ಡಹಳ್ಳಿ",
      "ಚಾಪುರ",
      "ಕೆಂದನಹಳ್ಳಿ",
      "ಆಲಂಬಗಿರಿ",
      "ಪೆರಮಾಚನಹಳ್ಳಿ",
      "ಮುನುಗನಹಳ್ಳಿ",
      "ನಾಯಿಂದ್ರಹಳ್ಳಿ",
      "ವೆಂಕಟಾಪುರ",
    ],
    supervisor: {
      name: "Sri Harish",
      kannadaName: "ಶ್ರೀ ಹರೀಶ್",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9740704290",
    },
  },
  {
    beatNumber: 10,
    officers: [
      {
        name: "Sri Manjesh",
        kannadaName: "ಶ್ರೀ ಮಂಜೇಶ್",
        designation: "CPC-233",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-233",
        phone: "9880427018",
      },
      {
        name: "Smt. Simataj",
        kannadaName: "ಶ್ರೀಮತಿ ಸಿಮಾತಾಜ್",
        designation: "CPC-399",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-399",
        phone: "7892062227",
      },
    ],
    areas: [
      "Chikkakatigenhalli",
      "Hirekatigenhalli",
      "Rachapura",
      "Byalahalli",
      "Madarakallu",
      "Nernakallu",
      "Madabahalli",
      "Konganahalli",
      "Sriramapura",
      "Gunnahalli",
      "Muttukadahalli",
      "Karadigutta",
      "Jidarahalli",
      "Jangamapura",
      "Nayindrahalli & Colony",
    ],
    kannadaAreas: [
      "ಚಿಕ್ಕಕಟಿಗೇನಹಳ್ಳಿ",
      "ಹಿರೇಕಟಿಗೇನಹಳ್ಳಿ",
      "ರಾಚಾಪುರ",
      "ಬ್ಯಾಲಹಳ್ಳಿ",
      "ಮಾದರಕಲ್ಲು",
      "ನೆರ್ನಕಲ್ಲು",
      "ಮಡಬಹಳ್ಳಿ",
      "ಕೊಂಗನಹಳ್ಳಿ",
      "ಶ್ರೀರಾಮಪುರ",
      "ಗುನ್ನಹಳ್ಳಿ",
      "ಮುತ್ತುಕದಹಳ್ಳಿ",
      "ಕರಡಿಗುಟ್ಟ",
      "ಜೀದರಹಳ್ಳಿ",
      "ಜಂಗಮಪುರ",
      "ನಾಯಿಂದ್ರಹಳ್ಳಿ & ಕಾಲೋನಿ",
    ],
    supervisor: {
      name: "Sri Prakash",
      kannadaName: "ಶ್ರೀ ಪ್ರಕಾಶ್",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9980901874",
    },
  },
  {
    beatNumber: 11,
    officers: [
      {
        name: "Sri Nagaraj",
        kannadaName: "ಶ್ರೀ ನಾಗರಾಜ್",
        designation: "HC-40",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-40",
        phone: "9071504465",
      },
      {
        name: "Sri Ambreesh",
        kannadaName: "ಶ್ರೀ ಅಂಬರೀಶ್",
        designation: "CPC-147",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-147",
        phone: "8660363499",
      },
    ],
    areas: [
      "Kaivara, Banahalli",
      "Vaddahalli.T",
      "Akkimangala",
      "Subbarayanapete",
      "Virupakshapura",
      "Atturu",
      "Kadirapura",
      "Talagavara",
      "Vaijakuru",
      "T Hosahalli",
      "Marapalli",
      "Santekallahalli",
      "Mallikapura",
      "Hirepalya",
      "Birjenahalli",
      "Surappanahalli",
    ],
    kannadaAreas: [
      "ಕೈವಾರ, ಬನಹಳ್ಳಿ",
      "ವಡ್ಡಹಳ್ಳಿ.ಟಿ",
      "ಅಕ್ಕಿಮಂಗಲ",
      "ಸುಬ್ಬರಾಯನಪೇಟೆ",
      "ವಿರುಪಾಕ್ಷಪುರ",
      "ಅಟ್ಟೂರು",
      "ಕದಿರಾಪುರ",
      "ತಳಗವಾರ",
      "ವೈಜಕೂರು",
      "ಟಿ ಹೊಸಹಳ್ಳಿ",
      "ಮಾರಪಲ್ಲಿ",
      "ಸಂತೇಕಲ್ಲಹಳ್ಳಿ",
      "ಮಲ್ಲಿಕಾಪುರ",
      "ಹಿರೇಪಾಳ್ಯ",
      "ಬೀರ್ಜೇನಹಳ್ಳಿ",
      "ಸೂರಪ್ಪನಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Prakash",
      kannadaName: "ಶ್ರೀ ಪ್ರಕಾಶ್",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "9980901874",
    },
  },
  {
    beatNumber: 12,
    officers: [
      {
        name: "Sri Pavan Kumar",
        kannadaName: "ಶ್ರೀ ಪವನ್ ಕುಮಾರ್",
        designation: "CPC-194",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-194",
        phone: "9739466834",
      },
      {
        name: "Ku. Soumya",
        kannadaName: "ಕು. ಸೌಮ್ಯ",
        designation: "MPC-395",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-395",
        phone: "8970256947",
      },
    ],
    areas: [
      "B.Vaddahalli",
      "Mastenahalli",
      "Jangamashigehalli",
      "Doddakondrahalli",
      "Chikkakondrahalli",
      "Mylapura",
      "Gubalahalli",
      "Nagadenahalli",
      "Bommakallu",
      "Doddaguttahalli",
      "Chikkaguttahalli",
      "Budaguru",
      "Shyamaravahosapete",
      "Kempadenahalli",
      "Hulugummanahalli",
      "Buragamakalhalli",
      "Kavalugaanahalli",
      "Narayanahalli",
    ],
    kannadaAreas: [
      "ಬಿ.ವಡ್ಡಹಳ್ಳಿ",
      "ಮಸ್ತೇನಹಳ್ಳಿ",
      "ಜಂಗಮಶಿಗೇಹಳ್ಳಿ",
      "ದೊಡ್ಡಕೊಂದ್ರಹಳ್ಳಿ",
      "ಚಿಕ್ಕಕೊಂದ್ರಹಳ್ಳಿ",
      "ಮೈಲಾಪುರ",
      "ಗೂಬಲಹಳ್ಳಿ",
      "ನಾಗದೇನಹಳ್ಳಿ",
      "ಬೊಮ್ಮಕಲ್ಲು",
      "ದೊಡ್ಡಗುಟ್ಟಹಳ್ಳಿ",
      "ಚಿಕ್ಕಗುಟ್ಟಹಳ್ಳಿ",
      "ಬೂದಗೂರು",
      "ಶ್ಯಾಮರಾವಹೊಸಪೇಟೆ",
      "ಕೆಂಪದೇನಹಳ್ಳಿ",
      "ಹುಲುಗುಮ್ಮನಹಳ್ಳಿ",
      "ಬೂರಗಮಾಕಲಹಳ್ಳಿ",
      "ಕಾವಲುಗಾನಹಳ್ಳಿ",
      "ನಾರಾಯಣಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Veeregowda",
      kannadaName: "ಶ್ರೀ ವೀರೇಗೌಡ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "8050457557",
    },
  },
  {
    beatNumber: 13,
    officers: [
      {
        name: "Sri Madesh",
        kannadaName: "ಶ್ರೀ ಮಾದೇಶ್",
        designation: "HC-01",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-01",
        phone: "8453504997",
      },
      {
        name: "Smt. Supriya",
        kannadaName: "ಶ್ರೀಮತಿ ಸುಪ್ರಿಯಾ",
        designation: "MPC-394",
        kannadaDesignation: "ಎಂ.ಪಿ.ಸಿ-394",
        phone: "8792702281",
      },
    ],
    areas: [
      "Binganahalli",
      "Lakshmidevankote",
      "Upparapete",
      "Konapalli",
      "Amitaganahalli",
      "Tinakal",
      "Mallikarjunapura",
      "Seekunte",
      "Rayapalli",
      "Swarapalli",
      "A. Guttahalli",
    ],
    kannadaAreas: [
      "ಬಿಂಗಾನಹಳ್ಳಿ",
      "ಲಕ್ಷ್ಮಿದೇವನಕೋಟೆ",
      "ಉಪ್ಪಾರಪೇಟೆ",
      "ಕೋನಪಲ್ಲಿ",
      "ಅಮಿಟಗಾನಹಳ್ಳಿ",
      "ತಿನಕಲ್",
      "ಮಲ್ಲಿಕಾರ್ಜುನಪುರ",
      "ಸೀಕುಂಟೆ",
      "ರಾಯಪಲ್ಲಿ",
      "ಸ್ವಾರಪಲ್ಲಿ",
      "ಎ. ಗುಟ್ಟಹಳ್ಳಿ",
    ],
    supervisor: {
      name: "Sri Veeregowda",
      kannadaName: "ಶ್ರೀ ವೀರೇಗೌಡ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "8050457557",
    },
  },
  {
    beatNumber: 14,
    officers: [
      {
        name: "Sri Ramanjineya",
        kannadaName: "ಶ್ರೀ ರಾಮಾಂಜನೇಯ",
        designation: "HC-27",
        kannadaDesignation: "ಹೆಚ್.ಸಿ-27",
        phone: "9880295565",
      },
      {
        name: "Sri Basavaraj Tengi",
        kannadaName: "ಶ್ರೀ ಬಸವರಾಜ್ ಟೆಂಗಿ",
        designation: "CPC-456",
        kannadaDesignation: "ಸಿ.ಪಿ.ಸಿ-456",
        phone: "9740653018",
      },
    ],
    areas: [
      "Adepalli",
      "Vasantahalli",
      "Shingarepalli",
      "Muntakadirenahalli",
      "Dwarapalli",
      "Masilahalli",
      "Dhanamittenahalli",
      "Gaunahalli",
      "Gaunigadda",
    ],
    kannadaAreas: ["ಆದೇಪಲ್ಲಿ", "ವಸಂತಹಳ್ಳಿ", "ಶಿಂಗರೇಪಲ್ಲಿ", "ಮುಂತಕದಿರೇನಹಳ್ಳಿ", "ದ್ವಾರಪಲ್ಲಿ", "ಮಸಿಲಹಳ್ಳಿ", "ಧನಮಿಟ್ಟೆನಹಳ್ಳಿ", "ಗೌನಹಳ್ಳಿ", "ಗೌನಿಗಡ್ಡ"],
    supervisor: {
      name: "Sri Veeregowda",
      kannadaName: "ಶ್ರೀ ವೀರೇಗೌಡ",
      designation: "ASI",
      kannadaDesignation: "ಎ.ಎಸ್.ಐ",
      phone: "8050457557",
    },
  },
];

export default function ChintamaniRural() {
  // Transform the data into the expected format
  const transformedData = {
    beatDetails: beatPoliceInfo.map(beat => ({
      number: beat.beatNumber,
      villages: beat.areas.map((area, index) => ({
        en: area,
        kn: beat.kannadaAreas[index]
      })),
      officers: beat.officers.map(officer => ({
        name: {
          en: officer.name,
          kn: officer.kannadaName
        },
        designation: {
          en: officer.designation,
          kn: officer.kannadaDesignation
        },
        phone: officer.phone
      })),
      supervisor: {
        name: {
          en: beat.supervisor.name,
          kn: beat.supervisor.kannadaName
        },
        designation: {
          en: beat.supervisor.designation,
          kn: beat.supervisor.kannadaDesignation
        },
        phone: beat.supervisor.phone
      }
    })),
    supervisingOfficers: Array.from(new Set(beatPoliceInfo.map(beat => beat.supervisor.name))).map(supervisorName => {
      const supervisor = beatPoliceInfo.find(beat => beat.supervisor.name === supervisorName).supervisor;
      const supervisedBeats = beatPoliceInfo
        .filter(beat => beat.supervisor.name === supervisorName)
        .map(beat => beat.beatNumber)
        .join(", ");
      
      return {
        beats: supervisedBeats,
        name: {
          en: supervisor.name,
          kn: supervisor.kannadaName
        },
        designation: {
          en: supervisor.designation,
          kn: supervisor.kannadaDesignation
        },
        phone: supervisor.phone
      };
    })
  };

  return (
    <BeatPoliceLayout 
      beatData={transformedData}
      talukName={{
        en: "Chintamani Rural",
        kn: "ಚಿಂತಾಮಣಿ ಗ್ರಾಮೀಣ"
      }}
    />
  );
} 